### PR TITLE
Rename app to uuid_erl

### PR DESCRIPTION
**Pull request by jamhed**
The app name in hex.pm is uuid_erl, but internally it is just uuid. So, if I specify the dependency in rebar.config as uuid_erl rebar3 is confused, and installs it under two names (uuid, and uuid_erl). Next, if I try to run dialyzer, it says app 'uuid' is not found, and fails. Also, rebar3 displays a message like app 'uuid' is no longer needed. This patch is supposed ti make it coherent.

### CODE REVIEW

**Comment by okeuday** [comment]
@jamhed You have ran into a rebar3 bug that was discussed at https://github.com/erlang/rebar3/pull/1337 (and https://github.com/erlang/rebar3/issues/1290).  There is no need to change the uuid source code or application file to get this to work, though I am unsure of the best rebar3 release to use (still need to test it to find a decent version) but the links here should lead you to a working commit.

**Comment by obrok** [comment]
@okeuday I would like to ask you to reconsider this. `hex.pm` has a `uuid` lib that uses the same app name. So in a sense this is a namespace clash. It's normally not a problem, because one is unlikely to use both at the same time, but if a dependency of one's project uses either, one is also locked into that particular, as they cannot coexist at runtime.

**Comment by okeuday** [comment]
@obrok Historically, this repo existed before the hex.pm [uuid](https://hex.pm/packages/uuid) lib.  Due to the hex.pm `uuid` source code using Elixir, the modules could coexist because Elixir has an `Elixir.` prefix on the module names making the hex.pm `uuid` module become `Elixir.UUID`.  However, the potential to have name clashes in both Erlang and Elixir is a valid problem that can not be solved in this repo.

It is unlikely that a small project will have more than one module with the same name due to separate dependencies.  However, the potential for different dependencies to coexist with the same module names used and/or separate versions, when considering large projects is a problem specific to Erlang/OTP applications and modules.  In https://cloudi.org the https://github.com/CloudI/CloudI/blob/develop/src/lib/reltool_util/scope escript is used ([here](https://github.com/CloudI/CloudI/blob/1850fbff3437c19a59b706e329b3477bab025317/src/Makefile.am#L8-L81)) to add a `cloudi_x_` prefix to all external dependency Erlang modules (the modules that lack a `cloudi` prefix), which allows the same dependencies to be used with separate versions with their normal module names (if that is necessary with any source code that CloudI loads).  There currently doesn't appear to be a better way to approach the dependency problem than the `scope` escript for Erlang source code (and it currently doesn't process Elixir source code).

So your comment is good and helps to point-out a namespace problem in Erlang and Elixir that remains unsolved in both programming languages.  However, renaming this repo's module names and application name will not improve the situation.

**Comment by obrok** [comment]
Don't want to push you in any direction - I managed to solve my particular problem, so ultimately it's up to you as the maintainer to pick a direction or even if you want to engage with this issue at all. Let me just post a link to the relevant issue in elixir-lang for cross-reference: https://github.com/elixir-lang/elixir/issues/5232.

Thanks for all the good work!

**Pull request closed without merging**
